[package]
name = "icegraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icy = { path = "./icy" }
serde = "1.0.162"
serde_json = "1.0.96"
xid = "1.0.3"
