nodes:
  - name: Song
    fields:
      - name: title
        type: String
  - name: Artist
    fields:
      - name: name
        type: String
  - name: Album
    fields:
      - name: title
        type: String
edges:
  - name: By
    connections:
      - from: Song
        to: Artist
        name: SongIsBy
      - from: Album
        to: Artist
        name: AlbumIsBy
    fields:
      - name: weight
        type: f64
