[package]
name = "icy"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.2"
paste = "1.0.12"
rayon = "1.7.0"
rocksdb = { version ="0.20.1", features = ["multi-threaded-cf"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
xid = "1.0.3"
